### ISSUE TITLE
Maven Error org.springframework.boot not found

### ISSUE THREAD

**Issue by sylhare** [Sylhare/Rest_API#1]
Following the spring [tutorial](https://spring.io/guides/gs/rest-service/) to create a simple Rest API on java I encountered some issues with the Maven dependencies of `org.springframework.boot`.

It seems that it can't find them even though they exists and it should be working. I will investigate and see what configuration I've done wrong on either the [pom.xml](https://github.com/Sylhare/Rest_API/commit/8a894ab7995034d131162c24cf626ca74e9206d7#diff-65b48a6dda76b1ab485f6f7e99a5ada0) file, maven or intelliJ.

**Comment by Sylhare** [comment]
Sometime it can be a [proxy issue](https://www.mkyong.com/maven/how-to-enable-proxy-setting-in-maven/). So you can go in [{M2_HOME}/conf/settings.xml](url) and update the file by adding this part (uncomment and populate the proxy information).

```xml
<!-- proxies
   | This is a list of proxies which can be used on this machine to connect to the network.
   | Unless otherwise specified (by system property or command-line switch), the first proxy
   | specification in this list marked as active will be used.
   |-->
  <proxies>
    <!-- proxy
     | Specification for one proxy, to be used in connecting to the network.
     |
    <proxy>
      <id>optional</id>
      <active>true</active>
      <protocol>http</protocol>
      <username>proxyuser</</username>
      <password>proxypass</password>
      <host>proxy.host.net</host>
      <port>80</port>
      <nonProxyHosts>local.net|some.host.com</nonProxyHosts>
    </proxy>
    -->
  </proxies>
```

**Comment by Sylhare** [comment]
So I've found a solution in my case, I have updated the pom.xml accordingly. After looking around, I was missing a dependency that was not really highlighted on the spring website:

```xml
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-web</artifactId>
    <version>4.1.6.RELEASE</version>
</dependency>
```

Now everything is fine, the "import" are working.
